config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get '/home/about' => 'homes#about', as: "about"

  namespace :public do
    resources :books, only: [:new, :create, :index, :show, :update, :destroy] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :create, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
  	  get '/users/out' => '/public/users#out'
  	  patch '/users/quit' => '/public/users#quit'
    end

    get '/search', to: 'searches#search'
  end

  namespace :admin do
    resources :books, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  belongs_to :genre

  validates :title,presence:true
  validates :introduction,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  def index
    @books = Book.page(params[:page])
    @book = Book.new
  end
  def show
    @book = Book.find(params[:id])
    @book_comments = @book.book_comments
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to admin_books_path
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/views/admin/books/index.css.erb
.main-container {
  background-image: url("<%= asset_path('haikei.jpg') %>")
  height: 800px;
  background-size:cover;
}

app/views/admin/books/index.html.erb
<div class="main-container">
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-12 '>
        <h2>投稿一覧</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>タイトル</th>
              <th>ユーザー</th>
              <th>ジャンル</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to book.title, admin_book_path(book.id) %></td>
                <td><%= book.user.name %></td>
                <td><%= book.genre.name %></td>
              </tr>
            <% end %>
            <%= paginate @books %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-4'>
  		<h2>漫画詳細</h2>
      <table class='table'>
        <tr>
          <th>タイトル</th>
          <td><%= @book.title %></td>
        </tr>
        <tr>
          <th>ユーザー</th>
          <td><%= @book.user.name %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @book.genre.name %></td>
        </tr>
        <tr>
          <th>いいね数</th>
          <td><%= @book.favorites.count %></td>
        </tr>
        <tr>
          <th>コメント数</th>
          <td><%= @book.book_comments.count %></td>
        </tr>
        <tr>
          <th>レビュー</th>
          <td><%= @book.introduction %></td>
        </tr>
        <tr>
          <td><%= link_to 'Destroy', admin_book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %></td>
        </tr>
      </table>
    </div>
    <div class='col-lg-8'>
      <h2>コメント欄</h2>
      <table class='table table-hover table-inverse'>
        <div class='row'>
          <thead>
            <tr>
              <th>ユーザー</th>
              <th>コメント</th>
            </tr>
          </thead>
          <tbody>
            <% @book_comments.each do |book_comment| %>
              <tr>
                <td><%= book_comment.user.name %></td>
                <td><%= book_comment.comment %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>