config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get '/home/about' => 'homes#about', as: "about"

  namespace :public do
    resources :books, only: [:new, :create, :index, :show, :update, :destroy] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :create, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
  	  get '/users/out' => '/public/users#out'
  	  patch '/users/quit' => '/public/users#quit'
    end

    get '/search', to: 'searches#search'
  end

  namespace :admin do
    resources :books, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
    redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def index
    @genres = Genre.page(params[:page])
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
      flash[:notice] = "変更内容を更新しました。"
      redirect_to admin_genres_path
   else
      flash[:alert] = "変更内容に不備があります。"
      render :edit
   end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-3 mt-3 mb-3">
      <h2>ジャンル編集</h2>
    </div>
  </div>

  <div class="row justify-content-start">
    <div class= "col-1">
      <%= form_with model: @genre,url: admin_genre_path, method: :patch, local: true do |f| %>
    </div>
      <%= f.label "ジャンル名",class:"form-label" %>
    <div class="col-3">
      <%= f.text_field :name,class:"form-control" %>
    </div>
    <div class="col-md justify-content-around">
      <%=f.submit "変更を保存", class:"btn btn-success"%>
    </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row justify-content-start">
    <div class="col-5 ml-5">
      <h2>ジャンル一覧・追加</h2>
    </div>
  </div>
  <div class="row justify-content-start">
      <div class="col-7 mt-4">
          <%= form_with model: @genre,url: admin_genres_path,method: :post, remote: true do |f| %>
           <%= f.label :name,"ジャンル名"%>
           <%= f.text_field :name, id: "form", placeholder:"ジャンル名" %>
           <%= f.submit "新規登録", class:"btn btn-success" %>
          <% end %>
      </div>
  </div>
  <div class="row justify-content-start">
    <div class="col-7 mt-5">
      <table class="table">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success" %></td>
          </tr>
          <% end %>
        <%= paginate @genres %>
        </tbody>
      </table>
    </div>
  </div>
</div>