config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get '/home/about' => 'homes#about', as: "about"

  namespace :public do
    resources :books, only: [:new, :create, :index, :show, :update, :destroy] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :create, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
  	  get '/users/out' => '/public/users#out'
  	  patch '/users/quit' => '/public/users#quit'
    end

    get '/search', to: 'searches#search'
  end

  namespace :admin do
    resources :books, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-8'>
      <h2>ユーザー一覧</h2>
  　　<table class='table'>
        <thead>
          <tr>
            <th>画像</th>
            <th>ユーザー名</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
              <td><%= link_to user.name , admin_user_path(user.id), class: "user_#{user.id}" %></td>

              <td></td>
            </tr>
          <% end %>
          <%= paginate @users %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-4'>
      <h2>ユーザーページ</h2>
      <table class='table'>
        <tr><%= image_tag @user.get_profile_image, size:'100x100' %></tr>
        <tr>
      	  <th>ユーザー名</th>
      	  <th><%= @user.name %></th>
        </tr>
        <tr>
      	  <th>紹介文</th>
      	  <th><%= @user.introduction %></th>
        </tr>
        <tr>
          <th>フォロー数</th>
          <th><%= @user.followings.count %></th>
        </tr>
        <tr>
          <th>フォロワー数</th>
          <th><%= @user.followers.count %></th>
        </tr>
      </table>
    </div>
    <div class='col-md-8'>
      <h3>ユーザーの投稿</h3>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>タイトル</th>
            <th>ジャンル</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.genre.name %></td>
              <td></td>
              <td></td>
            </tr>
          <% end %>
          <tr>
            <td>
              <%= link_to "強制退会", admin_user_path(@user), method: :delete, class: "btn btn-danger ml-5" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>