config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get '/home/about' => 'homes#about', as: "about"

  namespace :public do
    resources :books, only: [:new, :create, :index, :show, :update, :destroy] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :create, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
  	  get 'followers' => 'relationships#followers', as: 'followers'
  	  get '/users/out' => '/public/users#out'
  	  patch '/users/quit' => '/public/users#quit'
    end

    get '/search', to: 'searches#search'
  end

  namespace :admin do
    resources :books, only: [:index, :show, :destroy]
    resources :users, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  belongs_to :genre

  validates :title,presence:true
  validates :introduction,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  def index
    @books = Book.page(params[:page])
    @book = Book.new
  end
  def show
    @book = Book.find(params[:id])
    @book_comments = @book.book_comments
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to admin_books_path
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
    redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def index
    @genres = Genre.page(params[:page])
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
      flash[:notice] = "変更内容を更新しました。"
      redirect_to admin_genres_path
   else
      flash[:alert] = "変更内容に不備があります。"
      render :edit
   end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def after_sign_in_path_for(resource)
      admin_genres_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    about_path
  end

  
  def after_sign_out_path_for(resource)
    about_path
  end
  
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-info">
  <nav class="navbar navbar-expand-lg border-bottom" style="background-color:#1e90ff">
    <div class='container mt-2'>
    	<div class='row'>
      	<div class='mx-auto'>
      		<p>
      		  <span style="font-size : 15pt">
      		   集まれ漫画の里!!
      		  </span><i class="fas fa-book-open"></i>
      		</p>
      	</div>
      </div>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-info">
  <nav class="navbar navbar-expand-lg border-bottom" style="background-color:#1e90ff">
    <div class="container">
      <div class="mr-5 border rounded p-2 bg-warning">
        <% if admin_signed_in? %>
          <%= link_to "集まれ漫画の里!", admin_users_path, class:"header-title navbar-brand text-white"%>
        <% else %>
          <%= link_to "集まれ漫画の里!!", root_path, class:"header-title navbar-brand text-white"%>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

        <!--管理者がログインしていた場合-->
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_books_path, class: 'nav-link text-white border rounded mr-2 bg-success' do %>
            <i class="fas fa-book-open"></i>マンガ
            <% end %>
          </li>
          <li>
            <%=  link_to admin_users_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-users"></i>ユーザー
            <% end %>
          </li>
          <li>
            <%=  link_to admin_genres_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-list-ul"></i>ジャンル
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-white border rounded ml-2 bg-success' do %>
            <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>

        <!--顧客側がログインした場合-->
        <% elsif user_signed_in? %>
           <li>
            <%=  link_to new_public_book_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-edit"></i>投稿する
            <% end %>
          </li>
          <li>
            <%= link_to public_user_path(current_user), class: 'nav-link text-white border rounded mr-2 bg-success' do %>
            <i class="fas fa-user"></i>マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to public_books_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-book-open"></i>マンガ
            <% end %>
          </li>
          <li>
            <%=  link_to public_users_path, class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-users"></i>ユーザー
            <% end %>
          </li>
          <li>
            <%= link_to  destroy_user_session_path, method: :delete, class: 'nav-link text-white border rounded ml-2 bg-success' do %>
            <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>

        <!--ログインしていない場合-->
        <% else %>
          <li>
            <%= link_to about_path, class: 'nav-link text-white border rounded mr-2 bg-success' do %>
            <i class="fas fa-link"></i>About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-white border rounded mx-2 bg-success' do %>
            <i class="fas fa-user-plus"></i>新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-white border rounded ml-2 bg-success' do %>
            <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.css.erb
.main-container {
  background-image: url("<%= asset_path('haikei.jp') %>")
  height: 800px;
  background-size:cover;
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atsusato</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <p id="notice"><%= notice %></p>
      <div class="d-flex justify-content-center mb-2">
        <%= render "public/searches/form" %>
      </div>
      <div class="main-container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>